export enum BadgeType {
    EXPLORATION = "EXPLORATION",
    HISTORY = "HISTORY",
    ACCOMPLISHMENT = "ACCOMPLISHMENT",
    ACHIEVEMENT = "ACHIEVEMENT",
    ACCOLADE = "ACCOLADE",
    GLADIATOR = "GLADIATOR",
    VETERAN = "VETERAN",
    PVP = "PVP",
    INVENTION = "INVENTION",
    DEFEAT = "DEFEAT",
    EVENT = "EVENT",
    OUROBOROS = "OUROBOROS",
    CONSIGNMENT = "CONSIGNMENT",
    DAY_JOB = "DAY_JOB",
    AE = "AE"
}
